# Generated by Django 2.2.6 on 2019-10-14 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoupload', '0002_auto_20191014_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='photoupload.PostSession'),
        ),
    ]
