# Generated by Django 2.2.6 on 2019-10-15 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoupload', '0004_auto_20191015_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='photoupload.PostSession'),
        ),
    ]
