# Generated by Django 2.2.6 on 2019-10-15 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoupload', '0005_auto_20191015_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='photos')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
            },
        ),
        migrations.AlterModelOptions(
            name='postsession',
            options={'verbose_name': 'session', 'verbose_name_plural': 'sessions'},
        ),
        migrations.RenameField(
            model_name='postsession',
            old_name='session_name',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.AddField(
            model_name='postimage',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photoupload.PostSession'),
        ),
    ]
